# Generated by Django 5.0.2 on 2024-02-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('BEBIDA', 'Bebida'), ('DESAYUNO', 'Desayuno'), ('ALIMENTO_FRITO', 'Alimento frito'), ('ALIMENTO_EMPAQUETADO', 'Alimento empaquetado'), ('POSTRE', 'Postre')], default='BEBIDA', max_length=20),
        ),
    ]
