# Generated by Django 5.0.2 on 2024-03-18 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_bebida'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='disponibilidad',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('BEBIDA', 'Bebida'), ('DESAYUNO', 'Desayuno'), ('ALIMENTO_FRITO', 'Alimento frito'), ('ALIMENTO_EMPAQUETADO', 'Alimento empaquetado'), ('POSTRE', 'Postre')], max_length=20),
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_proveedor', models.CharField(max_length=50)),
                ('producto_entregado', models.CharField(max_length=100)),
                ('cantidad_producto', models.PositiveIntegerField()),
                ('fecha_entrega', models.DateField()),
                ('pago_entrega', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='menu.producto')),
            ],
        ),
    ]
