# Generated by Django 5.0.2 on 2024-03-18 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_producto_disponibilidad_producto_fecha_entrega_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_estudiante', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('correoEstudiante', models.EmailField(max_length=254)),
                ('correoAcudiente', models.EmailField(max_length=254)),
            ],
        ),
    ]
