# Generated by Django 5.0.2 on 2024-03-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='correo_confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
