# Generated by Django 5.0.2 on 2024-03-19 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_estudiante_correo_confirmado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='correoAcudiente',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='correoEstudiante',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='UsuarioAcudiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_acudiente', models.EmailField(max_length=254, unique=True)),
                ('password_acudiente', models.CharField(max_length=128)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='menu.estudiante')),
            ],
        ),
    ]
