# Generated by Django 5.0.2 on 2024-03-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_estudiante_correoacudiente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='correoAcudiente',
            field=models.EmailField(max_length=128),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='correoEstudiante',
            field=models.EmailField(max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarioacudiente',
            name='correo_acudiente',
            field=models.EmailField(max_length=128),
        ),
    ]
