# Generated by Django 5.0.2 on 2024-04-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_alergia'),
    ]

    operations = [
        migrations.AddField(
            model_name='alergia',
            name='restricciones_comida',
            field=models.TextField(blank=True, null=True),
        ),
    ]
