# Generated by Django 5.0.2 on 2024-04-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_alergia_restricciones_comida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='correo_confirmado',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tipo_usuario',
            field=models.CharField(choices=[('estudiante', 'Estudiante')], default='estudiante', max_length=20),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cedula_estudiante',
            field=models.CharField(max_length=100),
        ),
    ]
