# Generated by Django 5.0.2 on 2024-04-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_remove_estudiante_correo_confirmado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('BEBIDA', 'Bebida'), ('DESAYUNO', 'Desayuno'), ('ALIMENTO_FRITO', 'Alimento frito'), ('ALIMENTO_EMPAQUETADO', 'Alimento empaquetado'), ('POSTRE', 'Postre'), ('ALMUERZO', 'almuerzo')], max_length=20),
        ),
    ]
