# Generated by Django 5.0.2 on 2024-04-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_venta_valor_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('BEBIDA', 'Bebida'), ('DESAYUNO', 'Desayuno'), ('ALIMENTO_FRITO', 'Alimento frito'), ('ALIMENTO_EMPAQUETADO', 'Alimento empaquetado'), ('POSTRE', 'Postre'), ('ALMUERZO', 'Almuerzo')], max_length=20),
        ),
    ]
