# Generated by Django 5.0.2 on 2024-04-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_producto_imagen_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
