# Generated by Django 5.0.2 on 2024-05-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0026_remove_pedido_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='nuevo',
            field=models.BooleanField(default=True),
        ),
    ]
