# Generated by Django 5.0.2 on 2024-05-08 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0027_pedido_nuevo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estudiante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.estudiante'),
            preserve_default=False,
        ),
    ]
