# Generated by Django 5.0.2 on 2024-05-26 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0029_remove_pedido_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='alergia',
            name='categoria',
            field=models.CharField(choices=[('BEBIDA', 'Bebida'), ('DESAYUNO', 'Desayuno'), ('ALIMENTO_FRITO', 'Alimento frito'), ('ALIMENTO_EMPAQUETADO', 'Alimento empaquetado'), ('POSTRE', 'Postre'), ('ALMUERZO', 'Almuerzo')], default='BEBIDA', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alergia',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.producto'),
            preserve_default=False,
        ),
    ]
